spring:
  application:
    name: user-service

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8080
  servlet:
    context-path: /user-service
  error:
    whitelabel:
      enabled: false
    include-message: always

logging:
  level:
    root: info

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json
