spring:
  application:
    name: RestWithSpringJPA

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8080
  servlet:
    context-path: /myapp
  error:
    whitelabel:
      enabled: false
    include-message: always

logging:
  level:
    root: info
