server:
  port: 8081
  servlet:
    context-path: /user-service
spring:
  application:
    name: user-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://config-server:8888
